### ISSUE TITLE
IntelliJ-Plugin: Line break is added for empty record

### ISSUE THREAD

**Issue by marschwar** [palantir/palantir-java-format#1075]
## What happened?
First of all thanks for your work. 
After upgrading from IntelliJ Ulitmate from 2023.3.6 -> 2024.1,  I noticed that records without a body are formatted differently.

Plugin Version: 

```java
// IntelliJ 2023.3.6
public record MyRecord(String name) {}
```

```java
// IntelliJ 2024.1
public record MyRecord(String name) {
}
```

For the latter one the command `./gradlew spotlessJavaCheck` fails.

## What did you want to happen?

I would like the IntelliJ plugin and the spotless checkt to produce the same results. Is there any workaround to achieve this?

**Comment by ash211** [comment]
Possibly related to https://github.com/palantir/palantir-java-format/issues/1068
