### ISSUE TITLE
Breaks on method reference instead of method call

### ISSUE THREAD

**Issue by dansanduleac** [palantir/palantir-java-format#130]
## What happened?

PJF sometimes prefers to break before a method reference:

(example with a hypothetical short column limit for clarity)
```java
Foo bar = someVariable.foo().map(ElementType
        ::someMethod);
```

## What did you want to happen?

```java
Foo bar = someVariable.foo()
        .map(ElementType::someMethod);
```

**Comment by tpetracca** [comment]
Big +1. Wasn't a fan of this before and after:
![image](https://user-images.githubusercontent.com/2554328/73190215-a6ecf880-40f3-11ea-8e22-f9696c99c12d.png)
