### ISSUE TITLE
Don't double-indent blocks followed by method reference

### ISSUE THREAD

**Issue by dansanduleac** [palantir/palantir-java-format#33]
this whole thing is indented because of the trailing `::get`, however I think we can special-case this kind of thing and allow it to flow right after the method e.g. 
```java
Suppliers.memoize(() -> {
    ...
})::get
```

_Originally posted by @dansanduleac in https://github.com/palantir/gradle-consistent-versions/pull/305/review_comment/create_

**Comment by iamdanfox** [comment]
Fixed in https://github.com/palantir/palantir-java-format/pull/44
