### ISSUE TITLE
Intellij plugin not working with Java 14+ language features

### ISSUE THREAD

**Issue by fawind** [palantir/palantir-java-format#427]
Upstream google-java-format issue: https://github.com/google/google-java-format/issues/533

Intellij uses a custom JDK which is still JDK11 based (at least for 2020.2 and lower). Based on that, the formatter will not load the Java14InputAstVisitor when run inside intellij ([code ref](https://github.com/palantir/palantir-java-format/blob/d393c62fcb16cedadf1a1f9e8b56641d6fdbcae2/palantir-java-format/src/main/java/com/palantir/javaformat/java/Formatter.java#L141-L152)).

As a result, the intellij plugin errors on files with java 14+ language features and does not format them. The plugin still works for files that don't use new language features.

As a workaround, you can run the formatter from command line, e.g. using `./gradlew format` when using [gradle-baseline](https://github.com/palantir/gradle-baseline).

It is also possible to manually switch the intellij runtime to one that uses jdk 15 ([following this guide](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)) which makes the formatter work as expected with java 14 language features. However this is not recommended as the intellij and other jdks are not 1:1 compatible.

**Comment by carterkozak** [comment]
I think the jetbrains jres have custom code to improve font rendering, last time I tried using a standard jre it was not very pretty. I wonder if we could bootstrap another JRE from the idea plugin for formatting?

**Comment by fawind** [comment]
With https://github.com/palantir/palantir-java-format/pull/562, we now run the formatter main in a separate JVM based on the current Intellij project JDK. This allows us to use higher versions than Java 11 and to also specify additional `--add-exports` args which are needed for Java 16+.

For now, we only enabled this codepath if a Java 16+ project JDK is used to gradually roll this out without affecting existing setups.

**Comment by fawind** [comment]
Following up on the previous comment, this should be fixed with version 2.9.0+. Closing this out.
