### ISSUE TITLE
maven plugin

### ISSUE THREAD

**Issue by tonycody** [palantir/palantir-java-format#540]
maven plugin support

This can be done by providing a Maven plug-in, which relies on the compile phase to perform uniform code style when no IDE plug-in is installed.

Rely on IDE plug-ins when they are used.

Take a look at the Spring Java Format project:https://github.com/spring-io/spring-javaformat

**Comment by dylanbaroody** [comment]
+1 on this

**Comment by ayushsangani** [comment]
really interested in this as well.

**Comment by carterkozak** [comment]
I think this would be very nifty in some open-source projects, however I don't have experience writing maven plugins. I'd be happy to accept a contribution if someone is interested in writing one :-)

**Comment by carterkozak** [comment]
I'd like to contribute palantir-java-format support to the spotless project, I've filed an issue asking if they'd accept such a contribution here https://github.com/diffplug/spotless/issues/1076

**Comment by carterkozak** [comment]
Added in spotless maven plugin 2.20.0, just released.

**Comment by carterkozak** [comment]
I’ll update the readme with a link to the spotless plugin tomorrow

**Comment by tonycody** [comment]
> 



> Added in spotless maven plugin 2.20.0, just released.

Where are the maven plug-ins?

**Comment by carterkozak** [comment]
Docs here: https://github.com/diffplug/spotless/tree/main/plugin-maven#palantir-java-format

**Comment by tonycody** [comment]
> Docs here: https://github.com/diffplug/spotless/tree/main/plugin-maven#palantir-java-format

![image](https://user-images.githubusercontent.com/6773121/149257373-e9ec4b18-3c60-4f00-a914-d48abceb5762.png)
Are you in there?

**Comment by tonycody** [comment]
> Added in spotless maven plugin 2.20.0, just released.

The Maven central is not deployed
