### ISSUE TITLE
Broken on Java 16 

### ISSUE THREAD

**Issue by bmarcaur** [palantir/palantir-java-format#548]
Using JDK 16: 
```
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 16.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.2+0, mixed mode, sharing)
```

Running task `generateMetrics` fails with: 
```
> class shadow.com.palantir.goethe.goethe.com.palantir.javaformat.java.JavaInput (in unnamed module @0x1bba56ab) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x1bba56ab
```

Bumping down to JDK 11 seems to fix the issue.

Errorprone had a similar issue and linked to their install docs: https://errorprone.info/docs/installation#jdk-16

**Comment by bmarcaur** [comment]
To also confirm, this worked on jdk 15:
```
openjdk version "15.0.4" 2021-07-20
OpenJDK Runtime Environment Zulu15.34+17-CA (build 15.0.4+5-MTS)
OpenJDK 64-Bit Server VM Zulu15.34+17-CA (build 15.0.4+5-MTS, mixed mode, sharing)
```

**Comment by carterkozak** [comment]
This is due to [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396)
We haven't adopted java 16 internally since the supported lifespan is too short for us to roll off in time, however we're beginning to work on Java 17 support.

**Comment by iamdanfox** [comment]
That JEP dangles some tantalising options:

> It will still be possible to use the --add-opens command-line option, or the Add-Opens JAR-file manifest attribute, to open specific packages.

https://openjdk.java.net/jeps/261#Packaging:-Modular-JAR-files - could this be as easy as just embedding a module-info.class file that specifies all the crazy --add-opens things this project needs? 

https://github.com/palantir/palantir-java-format/blob/409f42e4ec5c845ed475a130655bd88c7002df0c/build.gradle#L85

EDIT seems like I confused `--add-exports` with `--add-opens` - maybe this won't be so easy

**Comment by fawind** [comment]
Some relevant context from how google-java-format is tackling this: [issue](https://github.com/google/google-java-format/issues/612), [readme](https://github.com/google/google-java-format/tree/32a919618b937f7c9b60632ae54e59f76a0df183#jdk-16).

Basically their solution for running with Java16+ is that you have to run the formatter with `--add-exports` flags added. Bit unfortunate and we might have to do some hacky stuff to get this working as Gradle integration or with the intellij plugin. One option might be to do something like bootstrapping our own jre when trying to format some files so we can pass through our flags (as mentioned [here](https://github.com/palantir/palantir-java-format/issues/427#issuecomment-785144030)).

**Comment by fawind** [comment]
The latest version should work with Java 16+. However depending on how you invoke the formatter you need to add `--add-exports` flags due to [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396).

When running the formatter through Gradle, you can for example add the args to your `gradle.properties` file:
```properties
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```

The intellij plugin and integration with [palantir/goethe](https://github.com/palantir/goethe) will automatically add these flags for you.

Closing this issue for now. Please re-open if you run into further issues!

**Comment by raiju** [comment]
Note that I couldn't get goethe to add the flags in modern gradle (filed here: https://github.com/palantir/goethe/issues/91)
