### ISSUE TITLE
How does the lower JDK support it?

### ISSUE THREAD

**Issue by tonycody** [palantir/palantir-java-format#776]
com/palantir/javaformat/java/JavaFormatterOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by iamdanfox** [comment]
> this version of the Java Runtime only recognizes class file versions up to 52.0

[Bytecode 52](https://javaalmanac.io/bytecode/versions/) suggests you're running on Java 8.  palantir-java-format 1.x was compiled with Java 8, but in the [changelog for the 2.0.0 release](https://github.com/palantir/palantir-java-format/releases/tag/2.0.0) this project included the breaking change of requiring java 11 or newer to run the formatter.

**Comment by tonycody** [comment]
> > this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> [Bytecode 52](https://javaalmanac.io/bytecode/versions/) suggests you're running on Java 8. palantir-java-format 1.x was compiled with Java 8, but in the [changelog for the 2.0.0 release](https://github.com/palantir/palantir-java-format/releases/tag/2.0.0) this project included the breaking change of requiring java 11 or newer to run the formatter.

Can you explain this in the readme.md file?
