### ISSUE TITLE
Is the 120 character limit configurable (using spotless)

### ISSUE THREAD

**Issue by mtzagkarakis** [palantir/palantir-java-format#859]
Hi I just wanted to know if the 120 character limit for line width is configurable in any way. I am using spotless and maven. Thanks

**Comment by igouss** [comment]
We all use modern monitors, I think 120 chat limit is unreasonable low, I would like to be able to change it too.

**Comment by mtzagkarakis** [comment]
thanks @simschla

**Comment by fawind** [comment]
Sorry, but I don't think we are very keen on making this configurable at this point in time.

First of all, I'm not convinced that increasing the line length actually improves readability of the code. Aware that this is a very subjective topic and that people have different preferences here. There are certainly instances where the 120 characters are limiting, but when considering code across the board and that its read by different people, does going from a 120 to lets say a 150 character limit make a significant difference in readability besides being individual preference?

Secondly, being non-configurable and bringing a consistent code style to codebases is an explicit goal of the formatter. This simplicity and consistency has many benefits which would be reduced by adding more configuration options.
There have been similar discussions regarding the [google-java-formatter](https://github.com/google/google-java-format) (which this formatter is a fork of) and think we are holding a similar stance for now (i.e. see [their FAQ](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how) and [this response](https://github.com/google/google-java-format/pull/57#issuecomment-388125762) for reference).

While this draft PR (https://github.com/palantir/palantir-java-format/pull/896) for making the limit configurable looks pretty small and straight forward, there is a lot more to it to make it usable in production. First, the complexity of testing and potential support increases. But also, the formatter gets used in a variety of ways (i.e. through the CLI, Intellij plugin, Gradle/Maven plugins, Spotless integration, ...). All those integrations need to allow configuration. How do you keep these configurations in sync? And if you are a larger engineering organization, how do you enforce a configuration across all of your codebases?

Solving these problems adds a lot of complexity in both maintaining and operating the formatter. I'm not convinced that the benefits of having a larger line length outweigh the costs here.
