### ISSUE TITLE
JDK21 string templates not works

### ISSUE THREAD

**Issue by GrapeBaBa** [palantir/palantir-java-format#966]
## What happened?

If the code contains string templates, `spotlessApply` will throw errors.
## What did you want to happen?

should works fine.

**Comment by lost22git** [comment]
same problem

![Screenshot 2024-01-18 210927](https://github.com/palantir/palantir-java-format/assets/65008815/05d8b5b8-c11b-4944-bdff-710d33f60d7b)

**Comment by tisonkun** [comment]
Downstream reports - https://github.com/diffplug/spotless/issues/2046

**Comment by bmarwell** [comment]
Duplicate of https://github.com/palantir/palantir-java-format/issues/930

**Comment by cushon** [comment]
> Duplicate of #930

Maybe not necessarily? Text blocks and string templates are separate features, although they can be used together.

For what it's worth, there were some recent changes to google-java-format to add initial support for string templates, it's possible that well be helpful for palanti-java-format ([one](https://github.com/google/google-java-format/commit/b5feefe4ab4dbdbba393d769eb1815f26896104b), [two](https://github.com/google/google-java-format/commit/38de9c4e05bc871496c232c1ccbfc4be06a580e2), [three](https://github.com/google/google-java-format/commit/e946e82801eb5bbd52bea00355ba20450bc0725c))

**Comment by bmarwell** [comment]
You are right. It is a preview feature in JDK 21, got me confused :)

**Comment by mhagnumdw** [comment]
> You are right. It is a preview feature in JDK 21, got me confused :)

And in JDK 23: Remove the String Templates preview feature: https://bugs.openjdk.org/browse/JDK-8329949

**Comment by GrapeBaBa** [comment]
Thanks guys.
